project:
  type: website
  output-dir: docs

website:
  title: "Guillermo Perez Algorta Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/LuciaNico/ElbordeBlog
      - icon: twitter
        href: https://twitter.com/Guillermo_inUK
format:
  html:
    theme: minty
    css: styles.css

editor: visual

